// Copyright (C) 2023 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only

#ifndef QTIFREMOTEOBJECTSHELPER_GLOBAL_H
#define QTIFREMOTEOBJECTSHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

#ifndef QT_STATIC
#  if defined(QT_BUILD_IFREMOTEOBJECTS_HELPER_LIB)
#    define Q_IFREMOTEOBJECTSHELPER_EXPORT Q_DECL_EXPORT
#  else
#    define Q_IFREMOTEOBJECTSHELPER_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_IFREMOTEOBJECTSHELPER_EXPORT
#endif

QT_END_NAMESPACE

#endif // QTIFREMOTEOBJECTSHELPER_GLOBAL_H
