add_subdirectory(frontend)
add_subdirectory(backend_simulator)
add_subdirectory(backend_simulator_static)
add_subdirectory(cmdlistener)
if (QT_FEATURE_remoteobjects)
    add_subdirectory(backend_qtro)
    add_subdirectory(backend_qtro_static)
    add_subdirectory(simulation_server_qtro)
    add_subdirectory(server_qtro)
endif()
if (QT_FEATURE_mqtt)
    add_subdirectory(backend_mqtt)
    add_subdirectory(backend_mqtt_static)
    add_subdirectory(server_mqtt)
endif()
add_subdirectory(test)
