version: 2
tags: ["documentation"]
accept_configuration:
  condition: and
  conditions:
    - condition: property
      property: features
      not_contains_value: Disable
      # Disable building on windows aarch64
    - condition: or
      conditions:
        - condition: property
          property: host.arch
          not_equals_value: AARCH64
        - condition: property
          property: host.os
          not_equals_value: Windows

instructions:
  Build:
  - type: EnvironmentVariable
    variableName: BUILD_DOCUMENTATION
    variableValue: "1"
  # Detect an ASAN build and set an env variable for CMake
  - type: AppendToEnvironmentVariable
    variableName: COIN_ASAN_BUILD
    variableValue: "1"
    enable_if:
      condition: property
      property: features
      contains_value: UseAddressSanitizer
  # Detect python3 and make ifcodegen mandatory for all configs
  - type: AppendToEnvironmentVariable
    variableName: NON_QTBASE_CMAKE_ARGS
    variableValue: " -DPython3_EXECUTABLE={{.Env.PYTHON3_EXECUTABLE}} -DPython3_ROOT_DIR={{.Env.PYTHON3_PATH}} -DFEATURE_ifcodegen=ON"
  - type: AppendToEnvironmentVariable
    variableName: NON_QTBASE_TARGET_CMAKE_ARGS
    variableValue: " -DPython3_EXECUTABLE={{.Env.PYTHON3_EXECUTABLE}} -DPython3_ROOT_DIR={{.Env.PYTHON3_PATH}} -DFEATURE_ifcodegen=ON"
  # Enable compiled ifcodegen on all packaging configs
  - type: AppendToEnvironmentVariable
    variableName: NON_QTBASE_CONFIGURE_ARGS
    variableValue: " -compiled-ifcodegen"
    enable_if:
      condition: property
      property: features
      contains_value: Packaging
  # Enable Axivion_analysis for Qt
  - type: EnvironmentVariable
    variableName: AXIVION_ANALYSIS
    variableValue: "1"
    enable_if:
      condition: property
      property: features
      contains_value: Axivion_qtinterfaceframework
  - type: Rename
    sourcePath: "{{.SourceDir}}/coin/axivion/ci_config_common.json"
    targetPath: "{{.Env.HOME}}/axivion/ci_config_common.json"
    userMessageOnFailure: "Moving ci_config_common.json failed. Make sure you have included the file in coin/axivion/ -folder"
    enable_if:
      condition: property
      property: features
      contains_value: Axivion_qtinterfaceframework
  # Enable a lcov code-coverage build
  - type: AppendToEnvironmentVariable
    variableName: NON_QTBASE_CMAKE_ARGS
    variableValue: " -DIF_COVERAGE=ON"
    enable_if:
      condition: property
      property: features
      contains_value: lcov
  - type: Group
    instructions:
      - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"
  - type: Group
    instructions:
      - !include "{{qt/qtinterfaceframework}}/cmake_module_lcov_code_coverage.yaml"
    enable_if:
      condition: property
      property: features
      contains_value: lcov

  Test:
    - type: Group
      instructions:
        - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
        - !include "{{qt/qtbase}}/coin_module_test_docs.yaml"
