version: 2
tags: ["documentation"]
accept_configuration:
  condition: property
  property: features
  not_contains_value: Disable

instructions:
  Build:
  - type: EnvironmentVariable
    variableName: BUILD_DOCUMENTATION
    variableValue: "1"
  - type: AppendToEnvironmentVariable
    variableName: NON_QTBASE_CONFIGURE_ARGS
    variableValue: " -DPython3_ROOT_DIR={{.Env.PYTHON3_PATH}}"
    disable_if:
      condition: property
      property: features
      contains_value: UseConfigure
  - type: AppendToEnvironmentVariable
    variableName: NON_QTBASE_TARGET_CONFIGURE_ARGS
    variableValue: " -DPython3_ROOT_DIR={{.Env.PYTHON3_PATH}}"
    disable_if:
      condition: property
      property: features
      contains_value: UseConfigure
  - type: AppendToEnvironmentVariable
    variableName: NON_QTBASE_CMAKE_ARGS
    variableValue: " -DPython3_ROOT_DIR={{.Env.PYTHON3_PATH}}"
    enable_if:
      condition: property
      property: features
      contains_value: UseConfigure
  - type: AppendToEnvironmentVariable
    variableName: NON_QTBASE_TARGET_CMAKE_ARGS
    variableValue: " -DPython3_ROOT_DIR={{.Env.PYTHON3_PATH}}"
    enable_if:
      condition: property
      property: features
      contains_value: UseConfigure
  - type: AppendToEnvironmentVariable
    variableName: NON_QTBASE_CONFIGURE_ARGS
    variableValue: " -compiled-ifcodegen"
    enable_if:
      condition: property
      property: features
      contains_value: Packaging
  - type: Group
    instructions:
      - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
    - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
    - !include "{{qt/qtbase}}/coin_module_test_docs.yaml"
